import org.junit.Test;

import java.net.URL;

import static com.codeforsanjose.blic.Crawler.parseUrl;
import static org.junit.Assert.assertEquals;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'falconer_k' at '6/10/16 9:02 PM' with Gradle 2.11
 *
 * @author falconer_k, @date 6/10/16 9:02 PM
 */
public class ParseUrlTest {
    @Test public void noSchemaTest() {
        String dirtyUrl = "//main.com";
        URL res = parseUrl(dirtyUrl);
        assertEquals(res.toString(), "http://main.com");
    }

    @Test public void hasHttpTest() {
        String dirtyUrl = "http://main.com";
        URL res = parseUrl(dirtyUrl);
        assertEquals(res.toString(), "http://main.com");
    }

    @Test public void hasHttpsTest() {
        String dirtyUrl = "https://main.com";
        URL res = parseUrl(dirtyUrl);
        assertEquals(res.toString(), "https://main.com");
    }
}
